package distributedAuction;


/**
* distributedAuction/AuctionClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Wednesday, March 8, 2017 4:04:33 PM CST
*/

public interface AuctionClientOperations 
{
  void update (String userID, String text);
} // interface AuctionClientOperations
