package distributedAuction;

/**
* distributedAuction/AuctionClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Wednesday, March 8, 2017 4:04:33 PM CST
*/

public final class AuctionClientHolder implements org.omg.CORBA.portable.Streamable
{
  public distributedAuction.AuctionClient value = null;

  public AuctionClientHolder ()
  {
  }

  public AuctionClientHolder (distributedAuction.AuctionClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = distributedAuction.AuctionClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    distributedAuction.AuctionClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return distributedAuction.AuctionClientHelper.type ();
  }

}
