package distributedAuction;


/**
* distributedAuction/AuctionClientHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Wednesday, March 8, 2017 4:04:33 PM CST
*/

abstract public class AuctionClientHelper
{
  private static String  _id = "IDL:distributedAuction/AuctionClient:1.0";

  public static void insert (org.omg.CORBA.Any a, distributedAuction.AuctionClient that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static distributedAuction.AuctionClient extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (distributedAuction.AuctionClientHelper.id (), "AuctionClient");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static distributedAuction.AuctionClient read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AuctionClientStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, distributedAuction.AuctionClient value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static distributedAuction.AuctionClient narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof distributedAuction.AuctionClient)
      return (distributedAuction.AuctionClient)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      distributedAuction._AuctionClientStub stub = new distributedAuction._AuctionClientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static distributedAuction.AuctionClient unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof distributedAuction.AuctionClient)
      return (distributedAuction.AuctionClient)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      distributedAuction._AuctionClientStub stub = new distributedAuction._AuctionClientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
