package distributedAuction;


/**
* distributedAuction/UnknownID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Wednesday, March 8, 2017 4:04:33 PM CST
*/

public final class UnknownID extends org.omg.CORBA.UserException
{

  public UnknownID ()
  {
    super(UnknownIDHelper.id());
  } // ctor


  public UnknownID (String $reason)
  {
    super(UnknownIDHelper.id() + "  " + $reason);
  } // ctor

} // class UnknownID
