package distributedAuction;


/**
* distributedAuction/AuctionServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Wednesday, March 8, 2017 4:04:33 PM CST
*/

public interface AuctionServerOperations 
{
  String subscribe (String userID, distributedAuction.AuctionClient c, int clientType) throws distributedAuction.NameAlreadyUsed;
  void unsubscribe (String id, int clientType) throws distributedAuction.UnknownID;
  void comment (String id, String text) throws distributedAuction.UnknownID;
  boolean isAuctionEmpty ();
  void setID (String id);
  void viewHighestBidder (String ID);
  void offer (String ID, String name, String description, int price);
  void bid (String ID, int amount);
  void viewAuctionStatus (String id);
  void viewBidStatus (String id);
  String sell ();
} // interface AuctionServerOperations
