package distributedAuction;

/**
* distributedAuction/NameAlreadyUsedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Wednesday, March 8, 2017 4:04:33 PM CST
*/

public final class NameAlreadyUsedHolder implements org.omg.CORBA.portable.Streamable
{
  public distributedAuction.NameAlreadyUsed value = null;

  public NameAlreadyUsedHolder ()
  {
  }

  public NameAlreadyUsedHolder (distributedAuction.NameAlreadyUsed initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = distributedAuction.NameAlreadyUsedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    distributedAuction.NameAlreadyUsedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return distributedAuction.NameAlreadyUsedHelper.type ();
  }

}
